### ISSUE TITLE
Package distribution

### ISSUE THREAD

**Issue by alexei** [zapier/email-reply-parser#20]
I gather this package is no longer maintained by it's original authors. I think every user would benefit if either Zapier transferred ownership to another developer or one of the contributors (e.g. @DisruptiveLabs) renamed their fork and published it on PyPI.

Thoughts?

**Comment by roycehaynes** [comment]
@alexei - Are there issues in particular that you want addressed?

@bryanhelmig - Happy to own repo and maintain.

**Comment by alexei** [comment]
We have some issues with messages sent from Live email accounts (I think) that do not get parsed at all. The original message is not quoted in any way (i.e. no >) albeit the headers are included so I guess that's the culprit. I think this https://github.com/DisruptiveLabs/email-reply-parser/commit/6eac05f46cf90d109461bf6e6ff75cfb6c74d02c addresses that issue.

Besides that, the package published on PyPI hasn't been updated for a while.

**Comment by bryanhelmig** [comment]
Seems like we ought to at least bring in https://github.com/zapier/email-reply-parser/pull/19.

Also, perhaps it is appropriate for a CONTRIBUTORS.md? Would be happy to take some folks on to help maintain with @roycehaynes (I just (re?) added you @roycehaynes).

@kageurufu would you be open to maintaining?

**Comment by kageurufu** [comment]
I'd be happy to maintain this if you want

Also @alexei, our fork is currently on pypi as [py-email_reply_parser](https://pypi.python.org/pypi/py-email_reply_parser).

**Comment by bryanhelmig** [comment]
Awesome, I added you @kageurufu - let me know if you want me to push a new version to PyPi, we can look into some automated way to do that too. (Maybe via Travis? Not sure.)

**Comment by kageurufu** [comment]
https://docs.travis-ci.com/user/deployment/pypi is an easy way to turn that on, I'll go ahead and close #19, branch our changes seperately from readme/setup.py changes, and create a new PR for that.

**Comment by bryanhelmig** [comment]
Awesome!

**Comment by alexei** [comment]
Guys, you are amazing! Thank you!

**Comment by kageurufu** [comment]
v0.5.9 is now deployed on pypi, enjoy!

**Comment by alexei** [comment]
Awesome, thanks!
