### ISSUE TITLE
Travis-CI pypi distribution

### ISSUE THREAD

**Issue by kageurufu** [zapier/email-reply-parser#22]
https://docs.travis-ci.com/user/deployment/pypi

@bryanhelmig if you have pypi push access, do you have time to set this up later (or just travis encrypt the password,  and send that blob my way)?

**Comment by bryanhelmig** [comment]
Definitely - I'm catching up on stuff today/tomorrow.

**Comment by bryanhelmig** [comment]
Added via 0c63316041f7daa079f2ba99f6cabbc7f3c68c35

**Comment by kageurufu** [comment]
Awesome, thank you!

Deployed 0.5.9 successfully :)
