### ISSUE TITLE
global name `is_header` is not defined

### ISSUE THREAD

**Issue by sindbach** [zapier/email-reply-parser#28]
The current master `__init__.py` currently will throw out error for : 

```
    self.fragment = Fragment(is_quoted, line, headers=is_header)
    NameError: global name 'is_header' is not defined
```
As the error message stated, this is due to undefined variable `is_header` at : 

https://github.com/zapier/email-reply-parser/blob/master/email_reply_parser/__init__.py#L109-L115

I believe this [PR-27](https://github.com/zapier/email-reply-parser/pull/27) is an attempt to roll back and fix.
Could someone approve/resolve ? 
Thanks.

**Comment by roycehaynes** [comment]
@sindbach - yea, let me review conflicts and run tests and merge PR-27. Thanks for the call out.

**Comment by ttyS15** [comment]
https://github.com/zapier/email-reply-parser/commit/67a66f698ae8cb4cad6757fbcc55a39af35facd3#commitcomment-22276287

+1 

version 5.10.0 is corrupted
