### ISSUE TITLE
Pypi deployment failed

### ISSUE THREAD

**Issue by kageurufu** [zapier/email-reply-parser#47]
Can I get someone with Pypi permissions to either grant [my pypi](https://pypi.org/user/kageurufu/) maintainership over there, or verify the email for @zapier pypi account so new versions can be uploaded?

Thanks

@roycehaynes

**Comment by EvanPurkhiser** [comment]
Hi @kageurufu,

Is there anyone else from the Zapier team you might be able to @ for this :) looks like @roycehaynes has been pretty quiet on GitHub recently.

Thanks for opening this issue!

**Comment by roycehaynes** [comment]
@kageurufu @EvanPurkhiser - I don't have pypi permissions but can @bryanhelmig may be able to help here.

**Comment by EvanPurkhiser** [comment]
Any chance you could help @bryanhelmig ?

**Comment by kageurufu** [comment]
Oh awesome, congratulations!

Just let me know what I can do to help here

**Comment by BYK** [comment]
Another ping @bryanhelmig - not to annoy, just following up with other Sentry folks as this is one of the blockers of us to migrate to Python 3 🙂

**Comment by bryanhelmig** [comment]
@BYK Thanks for the reminder! 😄 Godspeed on the Python 3 migration! 🖖 

@kageurufu you should have just gotten a maintainer invite on https://pypi.org/project/email_reply_parser/!

**Comment by kageurufu** [comment]
Thank you! I've accepted, and I'm working on getting everything going so we can see a new release asap!

**Comment by bryanhelmig** [comment]
You're the best @kageurufu! Thank you!
